# Generated by Django 5.2 on 2025-04-20 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 9, 4, 34, 523575, tzinfo=datetime.timezone.utc)),
        ),
    ]
