# Generated by Django 5.2 on 2025-04-21 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 5, 8, 10, 294285, tzinfo=datetime.timezone.utc)),
        ),
    ]
