# Generated by Django 5.2 on 2025-04-19 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_test_end_date_checkquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 5, 46, 11, 956797, tzinfo=datetime.timezone.utc)),
        ),
    ]
