# Generated by Django 5.2 on 2025-04-19 07:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_test_description_alter_test_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkquestion',
            name='test',
        ),
        migrations.AddField(
            model_name='checkquestion',
            name='checktest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.checktest'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 7, 30, 36, 307926, tzinfo=datetime.timezone.utc)),
        ),
    ]
