# Generated by Django 5.2 on 2025-04-19 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_checkquestion_test_checkquestion_checktest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 10, 14, 54, 981614, tzinfo=datetime.timezone.utc)),
        ),
    ]
